require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  NewCops: enable

# ----------------------- Layout ----------------------

Layout:
  Max: 120

Layout/FirstArrayElementIndentation:
  Enabled: false

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - activemodel-extra_validations.gemspec

# ----------------------- RSpec -----------------------

RSpec/ExampleLength:
  Enabled: false

# ----------------------- Style -----------------------

Style/FrozenStringLiteralComment:
  Enabled: false
